### ISSUE TITLE
`seekTo(int milliseconds)` doesn't work if player is paused or not started.

### ISSUE THREAD

**Issue by nemr0** [SimformSolutionsPvtLtd/audio_waveforms#279] opened 2024-03-10 13:05 UTC
**Describe the bug**
`seekTo(int milliseconds)` doesn't work if player is paused or not started.

**To Reproduce**
1. Create a player controller
2. seek from slider of wave form or programatically using `seekTo(int milliseconds)`.

**Expected behavior**
Seek on slide or programatic seek from controller if paused or not started.

**Smartphone (please complete the following information):**
- Devices tested on: `iPhone 12 pro` , `iPhone 11` , `iPhone 15 pro` , `Samsung A23`
- OS: `iOS 17.0` , `Android 13.0`
- Flutter SDK version: `3.13.9`.
- Package version: `^1.0.4`

**Comment by Ujas-Majithiya** [comment] 2024-03-11 17:26
@nemr0 This is getting addressed in #272. Closing, since it's duplicate of #200.

**Closed by Ujas-Majithiya** 2024-03-11 17:26 UTC
