### ISSUE TITLE
Push to Pub.dev + Flutter 3.0

### ISSUE THREAD

**Issue by zzterrozz** [SimformSolutionsPvtLtd/audio_waveforms#49] opened 2022-05-23 15:27 UTC
Can you please push the last version to pub.dev + fix the flutter 3.0 warning?

**Comment by zzterrozz** [comment] 2022-07-04 22:50
@DevarshRanpara , [https://pub.dev/packages/audio_waveforms/changelog](https://pub.dev/packages/audio_waveforms/changelog) is still under version `audio_waveforms: ^0.1.1`

**Comment by DhavalRKansara** [comment] 2022-07-26 10:54
duplicate of #41

**Closed by DhavalRKansara** 2022-07-26 10:54 UTC
