### ISSUE TITLE
Microphone might be turned off

### ISSUE THREAD

**Issue by a1erons** [SimformSolutionsPvtLtd/audio_waveforms#82] opened 2022-08-17 22:27 UTC
Now working fine on iOS, but this is my error when trying to record on Android!

**Comment by ujas-m-simformsolutions** [comment] 2022-08-18 07:11
Duplicate of #73. Check [this](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/73#issuecomment-1200409384) comment to enable the microphone for the android emulator.

**Closed by ujas-m-simformsolutions** 2022-08-18 07:11 UTC
Labels: duplicate
