### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by loic-hamdi** [SimformSolutionsPvtLtd/audio_waveforms#248] opened 2023-09-19 19:42 UTC
Hi,
We please need web support for this package.
What is the roadmap on this feature?

**Comment by Luismi74** [comment] 2023-12-13 02:24
I would also like to know if there is any update on this?

**Comment by mukhtharcm** [comment] 2024-01-26 04:10
Did you guys got any solution?

**Comment by ujas-m-simformsolutions** [comment] 2024-03-04 13:32
Duplicate of #42.

**Closed by ujas-m-simformsolutions** 2024-03-04 13:32 UTC
Labels: duplicate, enhancement
