### ISSUE TITLE
Very slow animation

### ISSUE THREAD

**Issue by rr8733380** [SimformSolutionsPvtLtd/audio_waveforms#161] opened 2023-02-19 19:07 UTC
Is it possible to make the animation smoother? For example, update the current time more often? or change the frequency of updates yourself?

https://user-images.githubusercontent.com/121060849/219969076-c2fceb11-b53e-4728-a9da-9ba244caee9b.mov

**Comment by ujas-m-simformsolutions** [comment] 2023-02-20 11:42
This is something similar to #145. The duration is updated every 200 ms. And we are thinking of providing an enum from which user can update the frequency upto 50 ms. We are happy take any suggestion on this if you have any.

**Comment by ujas-m-simformsolutions** [comment] 2023-02-20 11:42
Keeping this issue open for now.

**Comment by rr8733380** [comment] 2023-02-20 11:46
I think it would be better if you could specify the update time yourself. 
For example:
`Duration(milliseconds: 10)`

**Comment by ujas-m-simformsolutions** [comment] 2023-02-20 12:24
@rr8733380 Actually the duration which is being updated is current duration which we get from native, so it is an expensive task and it will depend on device that how much time it takes to report duration from native to flutter. Also earlier I was thinking providing a parameter to update the frequency but the issuer suggested to by providing a parameter like this would make it complicated so I'm thinking adding enum for this with values containing like low,medium, high.

**Comment by rr8733380** [comment] 2023-02-20 12:56
ok. it's a good idea. when are you planning to implement this?

**Comment by ujas-m-simformsolutions** [comment] 2023-03-15 07:02
Right now, I'm doing a PR for this.

**Comment by ujas-m-simformsolutions** [comment] 2023-03-15 07:02
Closing this as duplicate of #118.

**Closed by ujas-m-simformsolutions** 2023-03-15 07:02 UTC
Labels: enhancement
