### ISSUE TITLE
Release Build failed due to verifyReleaseResources

### ISSUE THREAD

**Issue by ehsan097** [SimformSolutionsPvtLtd/audio_waveforms#65] opened 2022-07-22 06:14 UTC
Execution failed for task ':audio_waveforms:verifyReleaseResources

**Comment by DhavalRKansara** [comment] 2022-07-26 10:52
duplicate of #50

**Comment by DhavalRKansara** [comment] 2022-07-26 10:52
duplicate of #50

**Closed by DhavalRKansara** 2022-07-26 10:52 UTC
