### ISSUE TITLE
The Android music wave is inverted

### ISSUE THREAD

**Issue by csacchetti** [SimformSolutionsPvtLtd/audio_waveforms#108] opened 2022-10-01 22:15 UTC
I have a strange problem. While iOS shows the music wave correctly with the silence spaces at zero, Android seems to show it inverted, in fact right from the start, when I haven't started talking yet it is at maximum and if I start talking it drops proportionally.
I don't understand if I have done something wrong (but I use your example) or there is a real problem.
Any suggestion?

**Comment by csacchetti** [comment] 2022-10-03 08:16
I use normalizationFactor to obtain a good wave also in android

**Comment by jackwill99** [comment] 2022-10-08 03:33
Are you ok recording in iOS?? I also use this repo example but iOS can't record. If you are ok, can you share your code for iOS?

**Comment by ujas-m-simformsolutions** [comment] 2022-10-12 09:02
@jackwill99 Check [this](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/107#issuecomment-1258973451) out. And closing this since the issue is been resolved.

**Closed by ujas-m-simformsolutions** 2022-10-12 09:02 UTC

**Comment by guoz2013** [comment] 2022-10-20 16:43
How do you resolved the problem?

**Comment by csacchetti** [comment] 2022-10-20 19:01
I use normalizationFactor to obtain a good wave also in android
