### ISSUE TITLE
When I run the project, this error appears

### ISSUE THREAD

**Issue by RamiHI** [SimformSolutionsPvtLtd/audio_waveforms#95] opened 2022-09-11 13:30 UTC
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/audio_waveforms-0.1.5/lib/src/controllers/player_controller.dart:14:3: Error: Type 'Uint8List' not found.
  Uint8List? _bufferData;
  ^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/audio_waveforms-0.1.5/lib/src/controllers/player_controller.dart:17:3: Error: Type 'Uint8List' not found.
  Uint8List? get bufferData => _bufferData;
  ^^^^^^^^^

**Comment by ujas-m-simformsolutions** [comment] 2022-09-12 05:33
Duplicate of #93.

**Closed by ujas-m-simformsolutions** 2022-09-12 05:33 UTC
Labels: duplicate
