### ISSUE TITLE
AudioFileWaveforms not filling till end even after whole audio is played

### ISSUE THREAD

**Issue by saravp123** [SimformSolutionsPvtLtd/audio_waveforms#132] opened 2022-12-01 13:06 UTC
We are recording audio in m4a format in iOS and playing the same using AudioFileWaveForms.  The file is playing fine but the waveform doesn't get shaded till end even after entire audio is played and completed - See the 1st waveform in below screenshot
![Simulator Screen Shot - iPad Pro (10 5-inch) - 2022-12-01 at 18 34 46](https://user-images.githubusercontent.com/39334476/205060424-444022c3-ca16-47bd-af8a-189a2407a6ed.png)

**Comment by ujas-m-simformsolutions** [comment] 2022-12-02 05:37
Looks Duplicate of #121. But keeping open for now.

**Comment by ujas-m-simformsolutions** [comment] 2022-12-20 10:32
We have release 1.0.0 which will fix this issue so I'm closing this issue for now but if issue persist feel free to open a new issue

**Closed by ujas-m-simformsolutions** 2022-12-20 10:32 UTC
