### ISSUE TITLE
In iOS, can't not record audio. It works on Android. So, I clone github repo and test on iOS. Here is the output.Someone can help me??

### ISSUE THREAD

**Issue by jackwill99** [SimformSolutionsPvtLtd/audio_waveforms#110] opened 2022-10-07 20:07 UTC
flutter: Recorded file size: 0
2022-10-08 02:33:39.196986+0630 Runner[1427:289902] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(, Failed to prepare recording, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      AudioWaveformsInterface.preparePlayer (package:audio_waveforms/src/base/audio_waveforms_interface.dart:90:18)
<asynchronous suspension>
#3      PlayerController.preparePlayer (package:audio_waveforms/src/controllers/player_controller.dart:97:26)
<asynchronous suspension>
#4      _HomeState._startOrStopRecording (package:audio_waveforms_example/main.dart:315:9)
<asynchronous suspension>

**Comment by alphatero** [comment] 2022-10-09 03:51
I have same issue, use simple usage code didn't work too.

**Comment by ujas-m-simformsolutions** [comment] 2022-10-12 08:52
Duplicate of #107. Use sampleRate 44100 and bitRate 48000

**Closed by ujas-m-simformsolutions** 2022-10-12 08:52 UTC
Labels: duplicate
