### ISSUE TITLE
Generating audio waveforms with streamable link instead of downloading the file

### ISSUE THREAD

**Issue by sonigeez** [SimformSolutionsPvtLtd/audio_waveforms#221] opened 2023-05-30 10:12 UTC
- The problem is the inability to generate audio waveforms without downloading the audio file through a streamable link. Currently, users are required to download the entire audio file in order to generate the waveform, which can be time-consuming and resource-intensive and it doesn't scalable.

**Comment by ujas-m-simformsolutions** [comment] 2023-07-14 09:31
Duplicate of #210

**Closed by ujas-m-simformsolutions** 2023-07-14 09:31 UTC
Labels: duplicate
