### ISSUE TITLE
Class 'AudioRecorder' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult

### ISSUE THREAD

**Issue by hasanmhallak** [SimformSolutionsPvtLtd/audio_waveforms#57] opened 2022-06-26 18:54 UTC
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by premy** [comment] 2022-07-01 23:21
same here

**Comment by hasanmhallak** [comment] 2022-07-02 08:29
@premy I add a pull request that fix this issue, you can check that out.
#60

**Comment by han-tm** [comment] 2022-07-13 13:05
When this pull will merged?

**Comment by devDonald** [comment] 2022-07-16 00:50
Please who has solved this issue

**Comment by devDonald** [comment] 2022-07-16 00:50
@hasanmhallak please any help?

**Comment by DhavalRKansara** [comment] 2022-07-26 10:52
Duplicate of #50

**Closed by DhavalRKansara** 2022-07-26 10:52 UTC
