### ISSUE TITLE
iOS not working waves graph

### ISSUE THREAD

**Issue by mahesh-gubbi** [SimformSolutionsPvtLtd/audio_waveforms#117] opened 2022-10-19 12:58 UTC
Android is working fine but in iOS waves not coming. waves forming like  dots only,  please check let me know. thank you.

 ```
AudioWaveforms(
            enableGesture: true,
            size: Size(MediaQuery.of(context).size.width / .2, 50),
            recorderController: recorderController,
            waveStyle: const WaveStyle(
              waveColor: Colors.white,
              extendWaveform: true,
              showMiddleLine: false,
            ),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12.0),
              color: const Color(0xFF1E1B26),
            ),
            padding: const EdgeInsets.only(left: 18),
            margin: const EdgeInsets.symmetric(horizontal: 15),
          ),
```
![simulator_screenshot_70E684AD-3318-41B8-88A6-C16747F075EC](https://user-images.githubusercontent.com/115148874/196697151-15412736-7e03-4860-9e71-476effde960d.png)

![simulator_screenshot_1BB11F97-A078-49A1-8522-7AE4FC93684D](https://user-images.githubusercontent.com/115148874/196695502-e5db89f3-0483-4ceb-8aa9-b27a78537b46.png)

**Comment by lokesh-gam** [comment] 2022-10-20 07:01
Even I am facing the same issues in iOS, Please let me know if find any solution.

**Comment by mahesh-gubbi** [comment] 2022-10-21 05:04
Any Updates Team!

**Comment by ujas-m-simformsolutions** [comment] 2022-10-21 05:44
Most probably a duplicate of #107
@mahesh-gubbi try setting sampleRate to 44100 and bitrate to 48000.  If this doesn't work please your recorder controller config.

**Comment by ujas-m-simformsolutions** [comment] 2022-11-30 13:28
Closing this issue since issue seems to be resolved.

**Closed by ujas-m-simformsolutions** 2022-11-30 13:28 UTC

**Comment by dikshit1400** [comment] 2024-07-29 10:08
This Issue is not  Resolved - 
I am Not able to RUN into IOS 18.


 recorderController = RecorderController()
      ..androidEncoder = AndroidEncoder.aac
      ..androidOutputFormat = AndroidOutputFormat.mpeg4
      ..iosEncoder = IosEncoder.kAudioFormatMPEG4AAC
      ..sampleRate = 44100
      ..bitRate = 48000;🤡
      


Please help me
