### ISSUE TITLE
iOS : audio is only playing through phone earpiece not from the speaker 

### ISSUE THREAD

**Issue by sauravdpl** [SimformSolutionsPvtLtd/audio_waveforms#112] opened 2022-10-16 12:09 UTC
i have implemented using the example and audio is playing fine in android but in iOS it is only playing through earpiece not from phone speaker

**Comment by ujas-m-simformsolutions** [comment] 2022-10-17 13:58
Can you please share any changes you have made to the native or flutter code because by default sound should come from the speaker and earpiece both

**Comment by sauravdpl** [comment] 2022-10-17 14:01
I have not changed anything even though I have copied all the code from the example to my project for testing, but it did not work. Sound still coming from the earpiece. Even I have tested it on iPhone 7 plus, and iPhone 13

**Comment by ujas-m-simformsolutions** [comment] 2022-10-18 10:52
@sauravdpl I tried with the example app on iPhone 12 and I'm not able to reproduce it.  Do you have any suggestion to reproduce it?

**Comment by sauravdpl** [comment] 2022-10-18 16:52
> @sauravdpl I tried with the example app on iPhone 12 and I'm not able to reproduce it. Do you have any suggestion to reproduce it?

did you just run by cloning the from, or you made a new project and added the package on pubsec. If make a new project and add a package from pubsec then you can reproduce the issue

**Comment by awnigharbia** [comment] 2022-12-15 18:57
I have the same problem. Does anyone know a solution?

**Comment by ujas-m-simformsolutions** [comment] 2023-01-20 08:32
As mentioned in the #153 this can be resolved by using audio_session package and setting the `avAudioSessionCategoryOptions` to `defaultToSpeaker`.

**Closed by ujas-m-simformsolutions** 2023-01-20 08:32 UTC
Labels: bug
