### ISSUE TITLE
Unhandled Exception: Exception: PlatformException(, Failed to prepare recording, null, null)

### ISSUE THREAD

**Issue by trustadekoye** [SimformSolutionsPvtLtd/audio_waveforms#130] opened 2022-11-30 11:35 UTC
I get this error when I try to play an audio I just recorded, Both on Simulator and real device

/
void startRecording(
      RecorderController recorderController,
      PlayerController playerController1,
      BuildContext context,
      String? path,
      AnimationController controller) async {
    try {
      if (await recorderController.checkPermission()) {
        if (Platform.isAndroid) {
          await recorderController.record();
        } else {
          Directory appDirectory = await getTemporaryDirectory();
          final file = File('${appDirectory.path}/tmp.m4a');
          await recorderController.record(file.path);
        }

        isRecording = recorderController.isRecording;

        notifyListeners();
      }
    } catch (e) {
      if (kDebugMode) {
        print(e);
      }
    }
   

    // isRecording = !isRecording;

    notifyListeners();
  }

  //stop recording
  void stopRecording(
      RecorderController recorderController,
      PlayerController playerController,
      BuildContext context,
      String? path,
      AnimationController controller) async {
    //stop

    try {
      recorderController.reset();
      final path = await recorderController.stop(false);
      Directory appDirectory = await getTemporaryDirectory();
      final file = File('${appDirectory.path}/tmp.m4a');
      await playerController.preparePlayer(file.path);
      isRecording = false;
      showWaveBubble = true;
      notifyListeners();
    } catch (e) {
      throw Exception(e);
    }
    // debugPrint('isRecording is $isRecording');
    notifyListeners();
  }

**Comment by ujas-m-simformsolutions** [comment] 2022-11-30 13:26
Duplicate of #107. Please follow [this](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues/107#issuecomment-1258973451)

**Closed by ujas-m-simformsolutions** 2022-11-30 13:26 UTC

**Comment by Androidsignal** [comment] 2022-12-12 12:23
@ujas-m-simformsolutions any solution found ?
