### ISSUE TITLE
does it support to play audio from url ?

### ISSUE THREAD

**Issue by bermohmtnm** [SimformSolutionsPvtLtd/audio_waveforms#210] opened 2023-04-28 21:49 UTC
does it support to play audio from url ?

**Comment by FaureAlexis** [comment] 2023-04-30 14:49
Currently no, you must provide your own implementation : 
```dart
Future<String> downloadAudioFromUrl(String url) async {
  final dir = await getApplicationDocumentsDirectory();
  final path = dir.path;
  final file = File('$path/file.wav');
  final response = await http.get(Uri.parse(url));
  await file.writeAsBytes(response.bodyBytes);
  return file.path;
}
```

**Comment by toufiksalhi** [comment] 2023-05-03 16:03
same issue

**Comment by toufiksalhi** [comment] 2023-05-03 16:35
> Currently no, you must provide your own implementation :
> 
> ```dart
> Future<String> downloadAudioFromUrl(String url) async {
>   final dir = await getApplicationDocumentsDirectory();
>   final path = dir.path;
>   final file = File('$path/file.wav');
>   final response = await http.get(Uri.parse(url));
>   await file.writeAsBytes(response.bodyBytes);
>   return file.path;
> }
> ```


this is not good for user experience each time he wanna hear the audio he will found a file of it in his phone ! 
فا

**Comment by campfire5** [comment] 2023-05-09 12:43
This feature is very urgent.

**Comment by campfire5** [comment] 2023-05-09 12:43
May we can just have the ability to play it from url, and never mind the wave data, I mean we can still pass the wave data manually.

**Comment by benedictleekw** [comment] 2023-05-29 14:50
Please prioritize on this feature if possible. Being able to play audio without downloading the audio file would be a huge plus

**Comment by ujas-m-simformsolutions** [comment] 2023-08-16 13:26
Duplicate of #54

**Closed by ujas-m-simformsolutions** 2023-08-16 13:26 UTC
