### ISSUE TITLE
Android Recording file was not working at iOS 

### ISSUE THREAD

**Issue by dev-interviewbox** [SimformSolutionsPvtLtd/audio_waveforms#136] opened 2022-12-12 06:33 UTC
Hi 

I made a recording app before.
However, files recorded on Android were not played on the iPhone.

I installed the sample code on the Galaxy Note 20 to find the problem.

The recording was conducted in Note 20 and the files included in the path below were stored separately through Android Studio.

path : /data/user/0/com.simform.audio_waveforms_example/app_flutter/music.aac

After that, the saved file was run on the Mac and iPhone 12, but the recorded file was not played.

The file is stored in aac format and is playing normally in Android or Windows environments.

It is difficult to determine where the cause lies. I want the recording file to be played no matter which platform I play on
Rather than recording process it on the server, recording tries to process it through a flutter.

I'd appreciate it if you could share the method.

my flutter version - 3.3.9 / Tools • Dart 2.18.5 • DevTools 2.15.0

**Comment by ujas-m-simformsolutions** [comment] 2022-12-13 12:33
Hello @dev-interviewbox, can you try setting AndroidOutputFormat to `aac_adts`, sampleRate to `44100` and bitRate to `48000`. This combination should fix your issue.

**Comment by ujas-m-simformsolutions** [comment] 2023-01-20 08:40
closing this as duplicate of #113

**Closed by ujas-m-simformsolutions** 2023-01-20 08:40 UTC
Labels: duplicate
