### ISSUE TITLE
Recorded file is always returning zero bytes

### ISSUE THREAD

**Issue by N-sravan** [SimformSolutionsPvtLtd/audio_waveforms#114] opened 2022-10-18 13:48 UTC
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(, Failed to prepare recording, null, null).
I'm running your example code

**Comment by ujas-m-simformsolutions** [comment] 2022-10-19 05:29
Duplicate of #107.

**Closed by ujas-m-simformsolutions** 2022-10-19 05:29 UTC
Labels: duplicate
