### ISSUE TITLE
Build problems make it unusable

### ISSUE THREAD

**Issue by GRawhideMart** [SimformSolutionsPvtLtd/audio_waveforms#296] opened 2024-05-07 14:32 UTC
**Describe the bug**
Introducing this library leads to build errors. See screenshot for further details.

**To Reproduce**
1. Go to 'pubspec.yaml'
2. Add audio_waveforms: ^1.0.5 to the dependencies
3. Try to build for Android

**Expected behavior**
It should build the Android application

**Smartphone (please complete the following information):**
- Google Pixel 8
- Android
- Version 14

**Screenshots**
![image](https://github.com/SimformSolutionsPvtLtd/audio_waveforms/assets/62698128/5f19168d-d395-4800-82f3-00a5919fd152)

**Comment by Ujas-Majithiya** [comment] 2024-05-12 08:13
I don't see anything related audio waveform in the image you shared. Can you please share full exception?

**Comment by SamProell** [comment] 2024-06-25 12:26
this happens for me as well. Just adding the dependency in pubspec.yaml (not adding any code related to audio_waveforms)  leads to the build error. Apparently, this only happens with the latest version 1.0.5. With 1.0.4 the app builds just fine (although I haven't tested/added any audio_waveforms functionality just yet).

**Comment by agustin-garcia** [comment] 2024-11-05 14:18
Hello,
If I try the 1.1.1 version, I'm getting the error when building either by downloading the zip code or by copy&pasting the Example code from https://pub.dev/packages/audio_waveforms/example in a new Flutter project

Execution failed for task ':flutter_plugin_android_lifecycle:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':flutter_plugin_android_lifecycle:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\agust\AppData\Local\Android\sdk\platforms\android-34\core-for-system-modules.jar.
...
This is my tech stack:

Android Studio Ladybug | 2024.2.1 Patch 2
Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.26100.2161], locale en-US)
    • Framework revision 603104015d (12 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
Windows Version (Installed version of Windows is version 10 or higher)
Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.2)
    • Windows 10 SDK version 10.0.22621.0

**Comment by jay-simformsolutions** [comment] 2024-12-23 10:09
Hi @agustin-garcia, @SamProell, and @GRawhideMart, We have tried all the ways to reproduce this issue, but we cannot reproduce them.

So, Please share your full error code or terminal output. Also, please share pubspec.yaml with other dependencies versions.

**Comment by SamProell** [comment] 2024-12-23 10:14
i have moved on from that project a while ago and will not be able to reproduce the issue. I ended up not including waveform visualization at all.

**Comment by GRawhideMart** [comment] 2024-12-23 10:16
Same here. It's been a long time, so I just moved along with other options.

Cheers anyway for an awesome project!

Il giorno lun 23 dic 2024 alle ore 11:14 Samuel Pröll <
***@***.***> ha scritto:

**Comment by jay-simformsolutions** [comment] 2024-12-23 10:34
Ok. So, I am closing this issue. Feel free to create a new issue or re-open this if you face it again.

**Closed by jay-simformsolutions** 2024-12-23 10:34 UTC
Labels: more-info-required, waiting-for-response, in triage
