### ISSUE TITLE
flutter 3.22

### ISSUE THREAD

**Issue by senkia24** [SimformSolutionsPvtLtd/audio_waveforms#303] opened 2024-05-28 11:55 UTC
in flutter 3.22 playercontroller doesnt work correctly. All player has same instances

**Comment by egorOztmz** [comment] 2024-05-28 13:26
I have the same bug, as far as I realize it's working fine on debug mode but using same playercontroller instances at release mode. For release mode key string value isn't printed like before, now it only shows 'Instance of UniqueKey'. That string value is used for finding/filtering streaming players at source code instead of UniqueKey object itself, that's the issue.

**Comment by Nico3652** [comment] 2024-05-31 12:55
@egorOztmz  i have the exactly the same issue. 
How did you manage this ? Downgrading flutter ? 

My app is in production so this is very important for me. Thanks in advance

**Comment by egorOztmz** [comment] 2024-05-31 13:24
Unfortunately yes @Nico3652, we downgraded flutter to 3.19.6 until this is fixed hopefully.

**Comment by kresovic-milos** [comment] 2024-05-31 22:01
+1

**Comment by lyingjack** [comment] 2024-06-17 18:51
+1

**Comment by lyingjack** [comment] 2024-06-17 19:19
+1

**Comment by ubaidxdev** [comment] 2024-07-04 10:34
> Unfortunately yes @Nico3652, we downgraded flutter to 3.19.6 until this is fixed hopefully.

The issue is fixed in the package or the issue is fixed when you downgraded the flutter to 3.19.6

**Comment by ubaidxdev** [comment] 2024-07-04 10:34
> Unfortunately yes @Nico3652, we downgraded flutter to 3.19.6 until this is fixed hopefully.

The issue is fixed in the package or the issue is fiexed when you downgraded the flutter to 3.19.6

**Comment by doshpin** [comment] 2024-07-06 20:22
This seems like a flutter issue that was solved in the master channel:
https://github.com/flutter/flutter/issues/148401#issuecomment-2172720783

**Comment by mu7mmd** [comment] 2024-07-20 15:16
The issue happens only on Android release mode !

**Comment by ujas-m-simformsolutions** [comment] 2024-08-02 06:13
This issue has been resolved with #310. Currently it has been merged to main. For now, you can use the main branch in your pubspec.yaml until it has been released.

**Comment by VasuSinojia** [comment] 2024-09-11 12:34
@ujas-m-simformsolutions Please release the fix as a version if possible.

**Closed** 2024-10-14 06:11 UTC
