### ISSUE TITLE
seekTo(progress) is not working 

### ISSUE THREAD

**Issue by VivekMakwana24** [SimformSolutionsPvtLtd/audio_waveforms#104] opened 2022-09-23 15:03 UTC
Hello,

seekTo function is not working, Could you please check?

This is how I have used it

_currentPlayerController?.seekTo(Duration(seconds: double.parse(p0).truncate()).inMilliseconds);

Thanks

**Comment by Ujas-Majithiya** [comment] 2022-09-25 09:43
Hey @VivekMakwana24, Here are some cases `seekTo` won't work
* Negative duration
* Controller not initialized
* Audio is paused

**Comment by VivekMakwana24** [comment] 2022-09-26 07:42
Hello, @Ujas-Majithiya 

Thanks for quick reply,

As per your mentioned points, all cases are correct.

Let me share some screenshots for the implementation

`
1] This is how I am performing seekTo() operation
![Screenshot from 2022-09-26 12-33-24](https://user-images.githubusercontent.com/48508009/192219917-6325a75f-0ef9-4594-87cb-9d12d79620bb.png)

2] These are the logs of the duration I am passing in the seekTo methhd
![Screenshot from 2022-09-26 12-23-08](https://user-images.githubusercontent.com/48508009/192219987-e444106a-dcac-42fc-85fc-89a324261918.png)

3] This is the AudioFileWaveforms implementation
![Screenshot from 2022-09-26 12-44-36](https://user-images.githubusercontent.com/48508009/192220271-e50ebbd0-f875-46a3-92e2-c84d32904826.png)

`

Please let me know if you need anything else.

Thanks

**Comment by ujas-m-simformsolutions** [comment] 2022-09-27 04:51
@VivekMakwana24 The image of the code you have provided looks ok to me so it will require minimum reproducible code or your platform specification because with the example app it is not reproducible.

**Comment by VivekMakwana24** [comment] 2022-09-27 05:43
@ujas-m-simformsolutions 

I have tried my implementation with the example app,

I am checking on Android device 
Device Info :
- OnePlus 9R (Android 12)

The issue I found is when in my example I am using "..androidOutputFormat = AndroidOutputFormat.aac_adts" for recordController.

.androidOutputFormat = AndroidOutputFormat.mpeg -> Works Fine

.androidOutputFormat = AndroidOutputFormat.aac_adts -> Creates issue while performing seekTo

**Comment by ujas-m-simformsolutions** [comment] 2022-09-27 13:06
@VivekMakwana24 This plugin uses ExoPlayer to play audio on android. Now, some files won't be seekable due to [this](https://exoplayer.dev/troubleshooting.html#why-are-some-media-files-not-seekable). So your file might not contain a constant bitrate.

**Comment by VivekMakwana24** [comment] 2022-09-30 10:32
Okk, Is there any solution that you would propose?

**Comment by ujas-m-simformsolutions** [comment] 2022-10-12 09:00
@VivekMakwana24 I would suggest just using the audio format which works for you and if the default format doesn't work then try using 48k bitRate and 44.1k sample rate and if you find any solution then we are open for PR.

**Comment by ujas-m-simformsolutions** [comment] 2022-11-30 13:41
Closing this issue since provided audio doesn't have seek-able data. 

If you think this a mistake then feel free to create a new issue.

**Closed by ujas-m-simformsolutions** 2022-11-30 13:41 UTC
Labels: wontfix
