### ISSUE TITLE
Android error: Class 'AudioRecorder' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult

### ISSUE THREAD

**Issue by GreatEric** [SimformSolutionsPvtLtd/audio_waveforms#68] opened 2022-07-28 06:10 UTC
/Users/kkkkk/SDKS/flutter/.pub-cache/hosted/pub.dartlang.org/audio_waveforms-0.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt: (20, 1): Class 'AudioRecorder' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /Users/ericli/SDKS/flutter/.pub-cache/hosted/pub.dartlang.org/audio_waveforms-0.1.1/android/src/main/kotlin/com/simform/audio_waveforms/AudioRecorder.kt: (97, 5): 'onRequestPermissionsResult' overrides nothing

**Comment by DhavalRKansara** [comment] 2022-07-28 08:31
Duplicate of #50 
You will find the fixes in the latest release **0.1.3**

**Closed by DhavalRKansara** 2022-07-28 08:31 UTC
