### ISSUE TITLE
The player cannot read from network urls

### ISSUE THREAD

**Issue by dancb10** [SimformSolutionsPvtLtd/audio_waveforms#297] opened 2024-05-14 11:31 UTC
Basically, the player requires the file to be locally which is kinda strange in an environment where the audio file is remotely. Why is that?

**Comment by Ujas-Majithiya** [comment] 2024-05-15 20:32
This choice was made because we do not support extracting waveform from a remote audio file and we might support playing audio remote audio files but there is some refactoring needed for it.

**Comment by Ujas-Majithiya** [comment] 2024-05-15 20:33
Closing this as duplicate of #54

**Closed** 2024-05-15 20:33 UTC
Labels: duplicate
