### ISSUE TITLE
Add play feature

### ISSUE THREAD

**Issue by ablbol** [SimformSolutionsPvtLtd/audio_waveforms#206] opened 2023-04-10 20:00 UTC
Thanks for this grate package.
Could you please add PLAY feature to this package so that when the recording is paused or stopped, then the user can PLAY the recording before sending it to the cloud.  You can see this feature in apps like WhatsApp.

**Comment by ujas-m-simformsolutions** [comment] 2023-04-14 06:30
duplicate of #199.

**Closed** 2023-04-14 06:30 UTC
Labels: duplicate
